version: '3.8'
services:
  app_dev:
    container_name: boilerplate-nest-dev
    image: boilerplate-nest-dev
    build:
      context: .
      target: development
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - app_mongodb_dev
      - app_redis_dev
    env_file:
      - .env.development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    restart: unless-stopped

  app_mongodb_dev:
    container_name: ${DATABASE_HOST}
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:27017"
    volumes:
      - ./mongo-data:/data/db 
    restart: unless-stopped

  app_redis_dev:
    container_name: ${REDIS_HOST}
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./redis-data:/data
    restart: always